name: workflow-1
on: workflow_dispatch
jobs:
  sample-job:
    runs-on: ubuntu-latest
    steps:
      - name: Terraform init
        run: echo "terraform init"
      - name: Terraform Validate
        run: echo "terraform validate"
      - name: Terraform Plan
        run: echo "terraform plan"
      - name: Terraform Apply
        run: echo "terraform apply"